global:
  scrape_interval:     15s
  evaluation_interval: 5s
rule_files:
  - prometheus.rules.yml

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9100', 'localhost:9101']
