global:
  scrape_interval:     15s

rule_files:
  - prometheus.rules.yml

scrape_configs:
  - job_name: 'node'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:5000']

alerting:
 alertmanagers:
   - scheme: http
     static_configs:
       - targets: ['127.0.0.1:9093']
